version: '3.1'

services:

  db:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: icc2021
    networks:
      - web

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 8080:8080
    networks:
      - web

networks:
  web:
    external: true
