version: '3.1'

services:

  db:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: icc2021

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
